FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jre-headless procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#mac albo windows
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

WORKDIR /app

RUN pip install --no-cache-dir pyspark==3.5.1 python-dotenv

COPY scripts/stream_processor.py /app/stream_processor.py

CMD ["python3"]